// C++ code
//

void setup()
{ 
pinMode(9,OUTPUT); 
pinMode(2,OUTPUT); 
pinMode(3,OUTPUT); 
pinMode(4,OUTPUT); 
pinMode(5,OUTPUT); 
pinMode(6,OUTPUT); 
pinMode(7,OUTPUT); 
pinMode(8,OUTPUT); 
pinMode(13,OUTPUT); 
pinMode(12,OUTPUT);
pinMode(11,OUTPUT);
} 
void numbers() 
{ 
//nine 
digitalWrite(9,LOW); 
digitalWrite(2,LOW); 
digitalWrite(3,LOW); 
digitalWrite(4,LOW); 
digitalWrite(5,HIGH); 
digitalWrite(6,LOW); 
digitalWrite(7,LOW);
digitalWrite(8,HIGH); 
delay(1000); 
//eight 
digitalWrite(9,LOW); 
digitalWrite(2,LOW); 
digitalWrite(3,LOW); 
digitalWrite(4,LOW); 
digitalWrite(5,LOW); 
digitalWrite(6,LOW); 
digitalWrite(7,LOW); 
digitalWrite(8,HIGH); 
delay(1000); 
//seven 
digitalWrite(9,LOW); 
digitalWrite(2,LOW); 
digitalWrite(3,LOW); 
digitalWrite(4,HIGH); 
digitalWrite(5,HIGH); 
digitalWrite(6,HIGH); 
digitalWrite(7,HIGH);
digitalWrite(8,HIGH);
delay(1000); 
//six 
digitalWrite(9,LOW); 
digitalWrite(2,HIGH); 
digitalWrite(3,LOW); 
digitalWrite(4,LOW); 
digitalWrite(5,LOW); 
digitalWrite(6,LOW); 
digitalWrite(7,LOW); 
digitalWrite(8,HIGH); 
delay(1000); 
//five 
digitalWrite(8,LOW); 
digitalWrite(2,HIGH); 
digitalWrite(3,LOW); 
digitalWrite(4,LOW); 
digitalWrite(5,HIGH); 
digitalWrite(6,LOW); 
digitalWrite(7,LOW); 
digitalWrite(8,HIGH); 
delay(1000); 
//four 
digitalWrite(9,HIGH); 
digitalWrite(2,LOW); 
digitalWrite(3,LOW); 
digitalWrite(4,HIGH); 
digitalWrite(5,HIGH); 
digitalWrite(6,LOW); 
digitalWrite(7,LOW); 
digitalWrite(8,HIGH); 
delay(1000); 
//Three 
digitalWrite(9,LOW); 
digitalWrite(2,LOW); 
digitalWrite(3,LOW); 
digitalWrite(4,LOW); 
digitalWrite(5,HIGH); 
digitalWrite(6,HIGH); 
digitalWrite(7,LOW);
digitalWrite(8,HIGH); 
delay(1000); 
//Two
digitalWrite(9,LOW); 
digitalWrite(2,LOW); 
digitalWrite(3,HIGH); 
digitalWrite(4,LOW); 
digitalWrite(5,LOW); 
digitalWrite(6,HIGH); 
digitalWrite(7,LOW); 
digitalWrite(8,HIGH); 
delay(1000); 
//one 
digitalWrite(9,HIGH); 
digitalWrite(2,LOW); 
digitalWrite(3,LOW); 
digitalWrite(4,HIGH); 
digitalWrite(5,HIGH); 
digitalWrite(6,HIGH); 
digitalWrite(7,HIGH); 
digitalWrite(8,HIGH); 
delay(1000); 
//zero
digitalWrite(9,LOW);
digitalWrite(2,LOW);
digitalWrite(3,LOW);
digitalWrite(4,LOW);
digitalWrite(5,LOW);
digitalWrite(6,LOW);
digitalWrite(7,HIGH);
digitalWrite(8,HIGH);
delay(1000);
} 
void loop() 
{ 
digitalWrite(13,HIGH); 
digitalWrite(12,LOW);
digitalWrite(11,LOW);
numbers(); 
digitalWrite(13,LOW);
digitalWrite(12,HIGH);
digitalWrite(11,LOW);
numbers(); 
digitalWrite(13,LOW);
digitalWrite(12,LOW);
digitalWrite(11,HIGH);
numbers();
}

